#!/usr/bin/env pwsh
# Cut an Sibyl release locally, by hand, on the GPU dev box.
#
# We deliberately do NOT use a self-hosted GitHub Actions runner: that would
# leave a GitHub-triggered build daemon running on a machine that holds your
# SSH key + HF token. Releases are infrequent, so we cut them manually instead.
# This script verifies, builds the installer (with the custom CUDA backend),
# and publishes a GitHub pre-release with the .exe attached.
#
# Prereqs on this machine: the CUDA Toolkit + VS Build Tools (for rebuild:llama),
# node_modules installed, and an authenticated `gh` CLI.
#
#   pwsh -File scripts/release.ps1                  # tests + GPU smoke + dist + publish
#   pwsh -File scripts/release.ps1 -SkipSmoke       # skip the GPU smoke gate
#   pwsh -File scripts/release.ps1 -DryRun          # build only; no tag, no publish
#   pwsh -File scripts/release.ps1 -KeepReleases 3  # keep 3 newest releases (default 2)
#   pwsh -File scripts/release.ps1 -CleanupTags     # also delete the git tags of pruned releases
#   pwsh -File scripts/release.ps1 -NoPrune         # skip the auto-prune step
param(
  [switch]$SkipSmoke,
  [switch]$DryRun,
  # Publish as a full/latest GitHub release instead of a pre-release. Use for
  # stable milestones (e.g. 1.0.0); omit for the usual 0.x-beta.N pre-releases.
  [switch]$Stable,
  # After a successful publish, keep only this many of the most recent releases
  # online and delete the rest. The in-app updater only reads the newest release's
  # latest.yml, so old releases are just storage. Must be >= 1.
  [int]$KeepReleases = 2,
  # Also delete the git tags of the releases that get pruned (local + remote).
  # Off by default — tags are cheap and let you re-cut an old version.
  [switch]$CleanupTags,
  # Skip the auto-prune step entirely (leave every release online).
  [switch]$NoPrune
)
if ($KeepReleases -lt 1) { throw "-KeepReleases must be >= 1 (got $KeepReleases)." }
$ErrorActionPreference = 'Stop'
Set-Location (Join-Path $PSScriptRoot '..')

if (-not $DryRun -and -not (Get-Command gh -ErrorAction SilentlyContinue)) {
  throw "GitHub CLI (gh) not found on PATH. Install it (and 'gh auth login') or pass -DryRun."
}

$version = (Get-Content package.json -Raw | ConvertFrom-Json).version
$tag = "v$version"
Write-Host "==> Releasing $tag" -ForegroundColor Cyan

# The published binary must correspond to the commit we tag, so refuse a dirty tree.
if (git status --porcelain) {
  throw "Working tree is dirty. Commit or stash changes before releasing."
}

Write-Host "==> Typecheck + unit tests"
npm run typecheck
npm test

if ($SkipSmoke) {
  Write-Warning "Skipping GPU smoke (-SkipSmoke). The installer will not be verified on a real GPU."
} else {
  Write-Host "==> GPU smoke (downloads a tiny model, loads on GPU, streams a reply)"
  npm run smoke
}

Write-Host "==> Building installer (electron-builder NSIS)"
npm run dist

$installer = "release/$version/Sibyl-$version-setup.exe"
if (-not (Test-Path $installer)) {
  throw "Expected installer not found at $installer"
}
Write-Host "==> Built $installer" -ForegroundColor Green

# The in-app auto-updater (electron-updater) needs latest.yml as a release asset
# to discover this version; the .blockmap enables differential downloads. Both are
# generated by electron-builder into release/<version>/ alongside the installer.
$latestYml = "release/$version/latest.yml"
if (-not (Test-Path $latestYml)) {
  throw "Expected update manifest not found at $latestYml (is `publish` set in electron-builder.yml?)"
}
$assets = @($installer, $latestYml)
$blockmap = "$installer.blockmap"
if (Test-Path $blockmap) {
  $assets += $blockmap
} else {
  Write-Warning "No .blockmap found — differential downloads will be unavailable for $tag."
}

if ($DryRun) {
  Write-Host "==> -DryRun: built but not tagging or publishing." -ForegroundColor Yellow
  Write-Host "    Would attach: $($assets -join ', ')"
  return
}

# Tag this commit (idempotent) and publish a pre-release with the installer +
# update metadata attached.
if (-not (git tag --list $tag)) {
  git tag -a $tag -m "Sibyl $tag"
}
git push origin $tag

$relFlag = if ($Stable) { '--latest' } else { '--prerelease' }
gh release create $tag @assets $relFlag --generate-notes --title "Sibyl $tag"
Write-Host "==> Published $(if ($Stable) { 'release' } else { 'pre-release' }) $tag" -ForegroundColor Green

# Auto-prune: keep only the $KeepReleases most recent releases online; delete the
# rest (release page + installer assets). The in-app updater only consults the
# newest release's latest.yml, so older releases are dead storage. Best-effort —
# the release already published, so a prune failure must not fail the script.
if (-not $NoPrune) {
  try {
    $releases = gh release list --limit 100 --json tagName,createdAt |
      ConvertFrom-Json |
      Sort-Object { [datetime]$_.createdAt } -Descending
    $stale = @($releases | Select-Object -Skip $KeepReleases)
    if ($stale.Count -eq 0) {
      Write-Host "==> Nothing to prune ($($releases.Count) release(s) <= keep $KeepReleases)."
    } else {
      foreach ($r in $stale) {
        Write-Host "==> Pruning old release $($r.tagName)"
        if ($CleanupTags) {
          gh release delete $r.tagName --yes --cleanup-tag
        } else {
          gh release delete $r.tagName --yes
        }
      }
      $tagNote = if ($CleanupTags) { ' (and their tags)' } else { '' }
      Write-Host "==> Pruned $($stale.Count) old release(s)$tagNote; kept the $KeepReleases most recent." -ForegroundColor Green
    }
  } catch {
    Write-Warning "Auto-prune failed (the release itself published fine): $_"
  }
}
